name: Send Alarm

on:
  schedule:
    - cron: '* * * * *'  # 매 1분마다
  workflow_dispatch:

jobs:
  send-alarm:
    runs-on: ubuntu-latest
    steps:
      - name: Call Netlify Function
        run: |
          curl -X POST https://gentle-douhua-15ac7d.netlify.app/.netlify/functions/send-alarm
